#!/bin/bash
if [ ! -f  vendor/responsive-nav.js ] ; then
    cp ../bower_components/responsive-nav/responsive-nav.js vendor/responsive-nav.js
fi

if [ ! -f  ../webroot/js/vendor/jquery.min.js ] ; then
    cp ../bower_components/jquery/dist/jquery.min.js ../webroot/js/vendor/jquery.min.js
fi

uglifyjs vendor/responsive-nav.js \
admin.js \
 -c -o ../webroot/js/admin.min.js
